<a href="https://colab.research.google.com/github/Jo2-j/study_NLPs/blob/main/codes/02_pytorchs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### pytorch 기본

In [2]:
import torch

In [4]:
torch.device('cuda:1')

device(type='cuda', index=1)

### torch 주요 datatype

In [5]:
x = torch.randn((10,5))

In [6]:
x

tensor([[-0.7436, -0.7708,  0.3488, -0.3933, -2.3455],
        [ 0.4477, -0.4583,  0.1491, -1.3395,  0.6125],
        [-0.5345, -0.6162, -2.0049,  0.4072, -1.3172],
        [ 0.4199,  0.5541,  2.1751,  0.4236, -0.8879],
        [ 1.2483,  0.7105, -0.3247,  0.0936, -0.4580],
        [ 1.0913,  0.5800,  0.8560, -2.7269, -0.7359],
        [ 1.1057,  2.2959, -1.6229,  0.0849, -1.5312],
        [ 0.4856,  0.5072, -1.3076,  0.7497, -0.8817],
        [ 0.7146, -0.4251, -0.1892,  0.0230,  0.2855],
        [ 1.0723, -1.0441,  0.0071, -1.1270,  0.5585]])

In [7]:
type(x), x.dtype, x.shape, x.device, x.size()

(torch.Tensor,
 torch.float32,
 torch.Size([10, 5]),
 device(type='cpu'),
 torch.Size([10, 5]))

In [8]:
x[0]

tensor([-0.7436, -0.7708,  0.3488, -0.3933, -2.3455])

In [9]:
# GPU인 cuda 사용

x_cuda = x.to('cuda:0')

In [10]:
x_cuda

tensor([[-0.7436, -0.7708,  0.3488, -0.3933, -2.3455],
        [ 0.4477, -0.4583,  0.1491, -1.3395,  0.6125],
        [-0.5345, -0.6162, -2.0049,  0.4072, -1.3172],
        [ 0.4199,  0.5541,  2.1751,  0.4236, -0.8879],
        [ 1.2483,  0.7105, -0.3247,  0.0936, -0.4580],
        [ 1.0913,  0.5800,  0.8560, -2.7269, -0.7359],
        [ 1.1057,  2.2959, -1.6229,  0.0849, -1.5312],
        [ 0.4856,  0.5072, -1.3076,  0.7497, -0.8817],
        [ 0.7146, -0.4251, -0.1892,  0.0230,  0.2855],
        [ 1.0723, -1.0441,  0.0071, -1.1270,  0.5585]], device='cuda:0')

In [11]:
type(x_cuda), x_cuda.dtype, x_cuda.shape, x_cuda.device

(torch.Tensor,
 torch.float32,
 torch.Size([10, 5]),
 device(type='cuda', index=0))

In [14]:
# x + x_cuda # 연산 영역이 달라 에러 발생
x.cuda() + x_cuda

tensor([[-1.4873, -1.5415,  0.6976, -0.7866, -4.6910],
        [ 0.8953, -0.9165,  0.2982, -2.6790,  1.2250],
        [-1.0691, -1.2324, -4.0098,  0.8144, -2.6343],
        [ 0.8399,  1.1081,  4.3502,  0.8472, -1.7759],
        [ 2.4965,  1.4210, -0.6495,  0.1871, -0.9161],
        [ 2.1826,  1.1601,  1.7120, -5.4538, -1.4717],
        [ 2.2114,  4.5919, -3.2458,  0.1698, -3.0624],
        [ 0.9713,  1.0144, -2.6152,  1.4995, -1.7634],
        [ 1.4292, -0.8501, -0.3784,  0.0459,  0.5711],
        [ 2.1446, -2.0883,  0.0141, -2.2539,  1.1170]], device='cuda:0')

In [16]:
x_cuda.T.shape  # numpy와 동일

torch.Size([5, 10])

In [17]:
x_cuda @ x_cuda.T # 행렬곱 (10*10)

tensor([[ 6.9248, -0.8374,  3.1025,  1.9354, -0.5516,  1.8384,  0.4001,  0.5650,
         -0.9485, -0.8569],
        [-0.8374,  2.6021, -1.6081, -0.8529, -0.2211,  3.5524, -1.8508, -1.7544,
          0.6306,  2.8112],
        [ 3.1025, -1.6081,  6.5858, -3.5847,  0.1874, -2.7980,  3.2994,  3.5162,
         -0.1075, -1.1385],
        [ 1.9354, -0.8529, -3.5847,  6.1823,  0.6578,  2.1398, -0.3980, -1.2588,
         -0.5907, -1.0861],
        [-0.5516, -0.2211,  0.1874,  0.6578,  2.3870,  1.5783,  4.2478,  1.8652,
          0.5228,  0.2331],
        [ 1.8384,  3.5524, -2.7980,  2.1398,  1.5783, 10.2375,  2.0444, -1.6908,
          0.0986,  3.2328],
        [ 0.4001, -1.8508,  3.2994, -0.3980,  4.2478,  2.0444, 11.4794,  5.2373,
         -0.3140, -2.1739],
        [ 0.5650, -1.7544,  3.5162, -1.2588,  1.8652, -1.6908,  5.2373,  3.5425,
          0.1443, -1.3554],
        [-0.9485,  0.6306, -0.1075, -0.5907,  0.5228,  0.0986, -0.3140,  0.1443,
          0.8092,  1.3423],
        [-0.8569,  